In [ ]:
#Numpy stands for Numerical Python 
    #Introduces data object called "ndarrays" :- table of elements of same data type
    #charateristics:- Homogenous, stores data in contiguos blocks in storage, fast
    #Vectorization: Single instruction Multiple data (performs single operation to all elements in it)

import numpy as np

# 1. Creating a 1D Array (Vector)
sales_list = [120, 150, 90, 200]
sales_array = np.array(sales_list) 

print("1D Array:", sales_array)
print("Type:", type(sales_array))
print("Data Type (dtype):", sales_array.dtype)
print("Shape:", sales_array.shape) # Returns (4,) meaning 4 elements in 1 dimension
print("-" * 30)

# 2. Creating a 2D Array (Matrix)
matrix_list = [[1, 2, 3], [4, 5, 6]]
matrix_array = np.array(matrix_list)

print("2D Array:\n", matrix_array)
print("Shape:", matrix_array.shape) # Returns (2, 3) -> 2 rows, 3 columns
print("Dimensions (ndim):", matrix_array.ndim) # Returns 2
print("Total Elements (size):", matrix_array.size) # Returns 6

arr = np.array([10,20,30,40,50],ndmin = 5)#also you can change the dimension using ndmin argument inside np.array()
print(arr)

#if elements of different types are stored in an ndarray, then it simply "Upcasts" the data type of the elements.
#For Example:

upcasted_ndarray = np.array([2,1.5,"Hello"])
print("The data type of elements got upcasted to:",upcasted_ndarray.dtype)
print(upcasted_ndarray)

1D Array: [120 150  90 200]
Type: <class 'numpy.ndarray'>
Data Type (dtype): int64
Shape: (4,)
------------------------------
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions (ndim): 2
Total Elements (size): 6
The data type of elements got upcasted to: <U32
['2' '1.5' 'Hello']


In [5]:
import numpy as np

# 1D Vector
arr_1d = np.array([1, 2, 3]) 

# 2D Matrix (2 rows, 3 columns)
arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6]]) 

# 3D Tensor (2 layers, 2 rows, 3 columns)
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                    [[7, 8, 9], [10, 11, 12]]])

print("--- 1. Placeholders ---")
#np.zeros(shape): creates a ndarray filled with zeros of given shape(default data type: float)
zeros_matrix = np.zeros((2, 3))
print("Zeros:\n", zeros_matrix)

#np.ones(shape): creates a ndarray filled with ones of given shape
ones_tensor = np.ones((2, 2, 2), dtype=np.int32) # Forcing integer type since default data type is float
print("\nOnes Tensor:\n", ones_tensor)

#np.empty(): allocates an empty placeholder matrix
garbage_matrix = np.empty((2, 2))
print("\nEmpty (Garbage values):\n", garbage_matrix)

print("\n--- 2. Sequences ---")
#np.arange(start,stop,step): generate numbers from 0 to 10, jumping by 2
step_sequence = np.arange(0, 11, 2)
print("arange (step size = 2):", step_sequence)

#np.linspace(start,stop,parts): generate exactly 5 numbers between 0 and 10(splits intervals evenly into several parts)
split_sequence = np.linspace(0, 10, 5)
print("linspace (5 items total):", split_sequence)

print("\n--- 3. Matrices & Constants ---")
# 3x3 standard identity matrix
ident = np.identity(3)
print("Identity Matrix:\n", ident)

# Shift diagonal UP by 1 position (k=1)
print("\nEye matrix:\n",np.eye(4, k=1))

# 3x4 matrix filled entirely with pi
pi_matrix = np.full((3, 4), 3.14159)
print("\nFull Matrix:\n", pi_matrix)

--- 1. Placeholders ---
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Tensor:
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]

Empty (Garbage values):
 [[2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314]]

--- 2. Sequences ---
arange (step size = 2): [ 0  2  4  6  8 10]
linspace (5 items total): [ 0.   2.5  5.   7.5 10. ]

--- 3. Matrices & Constants ---
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Eye matrix:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Full Matrix:
 [[3.14159 3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159 3.14159]]
