In [19]:
#indices help us to access individual elements from the array.
    #Positive indicing: starts from first element -> (0,n-1)
    #Negative indicing: starts from the last element -> (-n,-1)

import numpy as np

# indexing in one dimension
arr = np.array([10,20,30,40,50])
ele1 = arr[2]   #accessing an element via indexing extarcts its value and creates a new Python scalar object and does not return a direct mutable reference to the exact location
print(ele1)
#print(ele1.shape)   #returns () since shape of a single element is zero.
ele2 = arr[-3]
print(ele2)

#Practice 
# Question 1: Create a 1D array of numbers from 100 to 105. Access and print the first and the last element using a combination of positive and negative indexing.
arr1 = np.arange(100,106)
print("\nFirst Element:", arr1[0])
print("Last Element:", arr1[-1])

# Question 2: Write a snippet that changes the second element of an array to 99 and prints the updated array.
arr2 = np.array([1,2,3,4,5,6])
arr2[1] = 99
print("\n", arr2)

30
30

First Element: 100
Last Element: 105

 [ 1 99  3  4  5  6]


In [ ]:
#similarly 2 dimensional indexing
matrix = np.array([[10, 20, 30], 
                   [40, 50, 60]])
element = matrix[1, 2]  #matrix[1][2] works but highly inefficient as it creates an intermediate array
print(element)

#and three dimensional indexing
tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
element = tensor[1, 0, 1]
print(element)

60
6


In [ ]:
# Question 1: Given a 2D matrix of shape (3, 3) containing numbers 1 through 9, write the indexing code to extract the center element (5).
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Central element:",arr1[1][1])

# Question 2: Create a 3D array of shape (2, 2, 2) and extract the very last element using entirely negative indices.
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Last element:",arr2[-1][-1][-1])

Central element: 5
Last element: 8
(2, 2, 2)


In [ ]:
#slicing helps us to access a sub array(chunk of elements) from the original array
    #arr[start:stop:step]

#1D slicing
arr = np.array([10, 20, 30, 40, 50, 60])
sub_arr = arr[1:4]
print(sub_arr)

#array slices are not a copy of the elements of the array but a view of the original array itself unlike in lists.
#so changes made in the array slice also effect the original array
arr1 = np.array([1,2,3,4,5,6])
arr1[1:4] = [22,33,44]
print("Updated array:",arr1)

# Question 1: Given arr = np.array([5, 10, 15, 20, 25, 30]), write a slice that extracts [15, 20, 25].
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[2:5])

# Question 2: Create a 1D array of 10 elements and extract everything from the 5th element to the end of the array.
arr = np.arange(10)
print(arr[4:])
#arr[2:2] returns an empty array

[20 30 40]
Updated array: [ 1 22 33 44  5  6]
[15 20 25]
[4 5 6 7 8 9]


In [ ]:
#2D slicing
matrix = np.array([[10, 20, 30, 40],
                   [50, 60, 70, 80],
                   [90, 100, 110, 120]])
sub_matrix = matrix[0:2, 1:3]   #matrix[row_start:row_end, column_start:column_end]
                                #row-> top to bottom; column-> left to right
print(sub_matrix)

col_1 = matrix[:, 1]
print(col_1)

# Question 1: Given a 4x4 matrix containing values from 1 to 16, write a slice to extract the bottom-right 2x2 corner matrix.
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr1[2:,2:])

# Question 2: Write a slice that returns the entire 3rd row of any 2D matrix.
print
print(arr1[2,:])
print(arr1[2:3,:])
#using a slice (2:3) preserves the dimensions of the original array, whereas using a single integer (2) drops or collapses that dimension.

[[20 30]
 [60 70]]
[ 20  60 100]
[[11 12]
 [15 16]]
[ 9 10 11 12]
[[ 9 10 11 12]]


In [41]:
#step slicing
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
stepped = arr[1:7:2]
print(stepped,"\n")

#reverse slicing in 1d array
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1] #incredibly cheap operation with O(1) as its complexity since it does not move or copy any data in RAM
print(reversed_arr,"\n")

#reverse slicing in 2d array
matrix = np.array([[1, 2], 
                   [3, 4], 
                   [5, 6]])
flipped_rows = matrix[::-1, :]
print(flipped_rows,"\n")

#When using a negative step, your start index must be higher than your stop index 
#(e.g., arr[1:5:-1] returns an empty array [] because it can't step backward from index 1 to reach index 5).

# Question 1: Given arr = np.arange(10), write a slice that extracts all the odd numbers in their original order.
arr = np.arange(10)
print(arr[1::2],"\n")

# Question 2: Take a 3x3 matrix and reverse both its rows and columns simultaneously using slicing syntax.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[::-1,::-1])

[20 40 60] 

[5 4 3 2 1] 

[[5 6]
 [3 4]
 [1 2]] 

[1 3 5 7 9] 

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [49]:
#fancy slicing: used to access elements at random location using a list/array of indices of elements
arr = np.array([10, 20, 30, 40, 50, 60])
indices = [0, 4, 2]
result = arr[indices]   #returns the elements at the indices mentioned in the list indices
print(result,"\n")

#in 2d arrays
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6],
                   [7, 8]])
rows_to_get = [0, 3]
result = matrix[rows_to_get]
print(result,"\n")

#passing row and column arrays simultaneoulsy
matrix = np.array([[10, 20],
                   [30, 40],
                   [50, 60]])
rows = [0, 2]
cols = [1, 0]
result = matrix[rows, cols]
print(result,"\n")

#*IMP NOTE: fancy indexing only returns a COPY of the array. Any changes made to it won't be reflected in the original array
arr = np.array([1,2,3])
fancy = arr[[0,1]]
fancy[0] = 99
print(arr)
print(fancy,"\n")

# Question 1: Given arr = np.array([11, 22, 33, 44, 55, 66, 77]), use fancy indexing to extract an array containing [77, 11, 44].
arr1 = np.array([11, 22, 33, 44, 55, 66, 77])
print(arr1[[-1,0,3]],"\n")

# Question 2: Create a 3x3 matrix and use fancy indexing to modify the corner values (0,0) and (2,2) to zero at the same time.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = [0,2]
col = [0,2]
arr[rows,col] = 0
print(arr)

[10 50 30] 

[[1 2]
 [7 8]] 

[20 50] 

[1 2 3]
[99  2] 

[77 11 44] 

[[0 2 3]
 [4 5 6]
 [7 8 0]]


In [55]:
#Boolean indexing: used to return a boolean array holding boolean values for a certain constraint applied to the array
#returns a copy since elements may not always be contiguous
arr = np.array([10, 15, 20, 25, 30])
condition = arr > 20
result = arr[condition]
print("Condition Mask:", condition)
print("Filtered Result:", result,"\n")

#multiple conditions
arr = np.array([1, 5, 8, 12, 15, 20])
mask = (arr > 5) & (arr < 16)
result = arr[mask]
print(result,"\n")

#modification using conditioning
matrix = np.array([[1, -2], 
                   [-3, 4]])
matrix[matrix < 0] = 0
print(matrix,"\n")

# Question 1: Given arr = np.array([12, 7, 19, 24, 3, 10]), use boolean indexing to extract all the even numbers.
arr = np.array([12, 7, 19, 24, 3, 10])
even = arr%2 == 0
print(arr[even],"\n")

# Question 2: Create a 3x3 matrix containing values from 1 to 9. Write an expression that replaces all odd numbers with -1.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
odd_negat_unity = arr%2 != 0
arr[odd_negat_unity] = -1
print(arr)

Condition Mask: [False False False  True  True]
Filtered Result: [25 30] 

[ 8 12 15] 

[[1 0]
 [0 4]] 

[12 24 10] 

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]
