In [ ]:
#flatten() allows us to convert any multi-dimensional array into a single dimensional array and returns its deep copy to us

import numpy as np

#simple flattening: simply unrolls the array row-by-row
arr = np.array([[1,2,3],[5,6,7],[8,9,0]])
arr_flatten = arr.flatten()
print("Original Array:\n",arr,"\n")
print("Flatten Array:\n",arr_flatten,"\n")

#column-major flattening: unrolls the array column-by-column
arr_col_flatten = arr.flatten(order="F")    #by default its order="C"
print("Column Major Flattening:\n",arr_col_flatten)

Original Array:
 [[1 2 3]
 [5 6 7]
 [8 9 0]] 

Flatten Array:
 [1 2 3 5 6 7 8 9 0] 

Column Major Flattening:
 [1 5 8 2 6 9 3 7 0]


In [9]:
# Question 1: Create a 3D array of shape (2, 2, 2) with values from 1 to 8. Use flatten() to convert it to a 1D vector and print the result.
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr_3D_flatten = arr.flatten()
print("Flattened Array:\n",arr_3D_flatten)

# Question 2: Flatten a 3x3 matrix column-by-column (order='F') and access its 3rd element.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_flatten = arr.flatten(order="F")
print("\nFlattened Array:\n",arr_flatten)
print("\nThe third element of the flattened array is:",arr_flatten[2])

Flattened Array:
 [1 2 3 4 5 6 7 8]

Flattened Array:
 [1 4 7 2 5 8 3 6 9]

The third element of the flattened array is: 7


In [22]:
#ravel(): unlike flatten() it returns a view of the 1D array and does not creates a seperate array making it memory efficient.
# import numpy as np

matrix = np.array([[10, 20], 
                   [30, 40]])
raveled_arr = matrix.ravel()
print(raveled_arr)

matrix = np.array([[1, 2], 
                   [3, 4]])
raveled_arr = matrix.ravel()
raveled_arr[0] = 99    #data manipulated inside a raveled array is also reflected in the original array
print("\n",matrix)

#*IMP NOTE: ravel() returns a copy instead of view of the array in the case when the data is not stored in contiguous manner
#for example
arr = np.array([[1,2,3],[4,5,6]])
non_cont_arr = arr[::2,::]
raveled_arr = non_cont_arr.ravel()
print("\n",raveled_arr.base)    #.base is an attribute that tells if the object has its own memory or is it just a view
#.base returns None if it has its own memory else points to the object it is a view of

[10 20 30 40]

 [[99  2]
 [ 3  4]]

 [[1 2 3]
 [4 5 6]]


In [ ]:
# Question 1: Create a 3x3 matrix. Use ravel() to flatten it, and change the last element of the flattened array to 0. Print the original matrix to check the change.
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_ravel = arr.ravel()
arr_ravel[-1] = 0
print("Original array after changes:\n",arr)

# Question 2: Look up the memory layout of matrix.ravel(order='F')—does it behave differently regarding data modification?
arr = np.array([[1,2],[3,4],[5,6]])
arr_ravel_F = arr.ravel(order = "F")
arr_ravel_F[0] = 99
print("\nOriginal array after changes(no change):\n",arr)
#no change is observed since to access the array in Fortran order (order="F"), Python is forced to create a deep copy instead of returning a view

Original array after changes:
 [[10 20 30]
 [40 50 60]
 [70 80  0]]

Original array after changes(no change):
 [[1 2]
 [3 4]
 [5 6]]


In [23]:
#transpose(): it returns a view of a diagonally flipped array
# import numpy as np

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
transposed = matrix.transpose() #does not works on 1D arrays and returns the array itself unchanged
print("Original Matrix:\n",matrix)
print("\nTransposed Matrix:\n",transposed)

#shortcut for transpose
matrix = np.array([[10, 20], 
                   [30, 40]])
print("\n",matrix.T) 

#multidimesnional(D>2) transposing
tensor = np.ones((2, 3, 4))
transposed_tensor = tensor.transpose(2, 0, 1)   #switches the axis of the original array from (0,1,2) -> (2,0,1)
print("\n",transposed_tensor.shape)

Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]

 [[10 30]
 [20 40]]

 (4, 2, 3)


In [17]:
# Question 1: Create a 2D matrix of shape (4, 2). Transpose it using the .T shortcut and print its new shape.
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
t_arr = arr.T
print("Transposed array:\n",t_arr)

# Question 2: Create a 3D array of shape (1, 2, 3) and transpose it so its new shape becomes (3, 2, 1).
arr = np.array([[[1,2,3],[4,5,6]]])
t_arr = arr.transpose(2,1,0)
print("\nTransposed array shape:",t_arr.shape)

Transposed array:
 [[1 3 5 7]
 [2 4 6 8]]

Transposed array shape: (3, 2, 1)


In [ ]:
#reshape(): it creates a view with the shape of the array without changing any data inside it.
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print("Reshaped array:\n",reshaped_arr)

#using negative dimension: it automatically calculates the the remaining value
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped_arr = arr.reshape(2, -1)   #here it automatically decides that the number of columns must be 8/2=4
print("\nReshaped array:\n",reshaped_arr)

#multi-dimensional -> 1D
matrix = np.array([[10, 20], [30, 40]])
flattened = matrix.reshape(-1)
print("\n1D array:\n",flattened)

Reshaped array:
 [[1 2 3]
 [4 5 6]]

Reshaped array:
 [[1 2 3 4]
 [5 6 7 8]]

1D array:
 [10 20 30 40]


In [32]:
# Question 1: Create a 1D array containing numbers 1 to 12. Reshape it into a 3D array of shape (2, 2, 3). 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr_reshape = arr.reshape(2,2,3)
print("Reshape array:\n",arr_reshape)

# Question 2: Take a 2D array of shape (4, 3) and flatten it into a 1D array using reshape().
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr_1D = arr.reshape(-1)
print("\nReshaped Array:\n",arr_1D)

Reshape array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Reshaped Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#resize(): unlike reshape() which returns a ValueError when the number of elements does not remains same, resize() either repeats the elements or fill the new spaces with zeros.
import numpy as np

arr = np.array([1,2,3,4])
resized_arr = np.resize(arr,(2,3))  #to fill the vacant two spaces, it repeats the elements 1 and 2
print(resized_arr,"\n")  #original array is not affected

#in-place resizing: returns a view of the original array which underwent resizing unlike simple resizing. Also it fills the extra spaces with zeros 
Arr = np.array([1,2,3,4])
Arr.resize((2,4),refcheck=False)    #refcheck ensures if the array being resized is not refernced by any other variable or is not a refernce itself, 
#as in-place resizing leads to the memroy reference being broken or unstable
print(Arr,"\n")

#trimming of array while resizing.
arr1 = np.array([1,2,3,4,5,6])
arr = np.resize(arr1,(2,2))
print(arr,"\n")

[[1 2 3]
 [4 1 2]] 

[[1 2 3 4]
 [0 0 0 0]] 

[[1 2]
 [3 4]] 



In [14]:
# Question 1: Create an array containing [5, 10, 15]. Use np.resize() to build a 3x3 matrix out of it and print the result.
arr = np.array([5,10,15])
arr1 = np.resize(arr,(3,3))
print("Resized array:\n",arr1)

# Question 2: Take a 1D array of 6 elements and use the in-place .resize() method to expand its shape to (3, 4).
arr = np.array([1,2,3,4,5,6])
arr.resize((3,4),refcheck = False)
print("\nIn-Place Resized array:\n",arr)

Resized array:
 [[ 5 10 15]
 [ 5 10 15]
 [ 5 10 15]]

In-Place Resized array:
 [[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [ ]:
# =====================================================================
# RESHAPE vs RESIZE: QUICK CHEAT SHEET
# =====================================================================

# 1. Total Elements Constraint
# np.reshape() -> Total number of elements MUST stay exactly the same.
# np.resize()  -> Total number of elements CAN change (pads or repeats).

# 2. Memory Behavior (View vs Copy)
# np.reshape() -> Returns a VIEW. Modifying it changes the original array.
# np.resize()  -> Returns a COPY. Modifying it does NOT affect original.

# 3. In-Place Modification
# arr.reshape()-> Does NOT exist in-place (always returns a new array).
# arr.resize() -> Modifies array IN-PLACE (mutates the original memory).

# =====================================================================
# SIMPLE RESIZING vs IN-PLACE RESIZING
# =====================================================================

# 1. Syntax & Operation
# np.resize(arr, shape) -> SIMPLE: Returns a completely new array.
# arr.resize(shape)     -> IN-PLACE: Modifies the original array directly.

# 2. Memory Safety
# np.resize(arr, shape) -> SAFE. Leaves original array completely untouched.
# arr.resize(shape)     -> RISKY. Mutates original memory; requires refcheck=False if shared.

# 3. Missing Data Filling
# np.resize(arr, shape) -> REPEATS elements from the original array to fill gaps.
# arr.resize(shape)     -> PADS with zeros (0) to fill gaps.


In [ ]:
#squeeze(): returns a view by removes unneccessary nesting (removing single-dimensional entries from the shape of an array)
arr = np.array([[[1, 2, 3]]])
print("Original Array:",arr)
print("Original Shape:", arr.shape)
squeezed = np.squeeze(arr)
print("Squeezed Result:", squeezed)
print("New Shape:", squeezed.shape)

#targeting a particular axis to squeeze
arr = np.ones((1, 5, 1))
print("\nOriginal Shape:",arr.shape)
squeezed_axis0 = np.squeeze(arr, axis=0)    #axis=0 ensures that only first (0) axis gets squeezed
print("Squeezed Axis 0 Shape:", squeezed_axis0.shape)

#IMP NOTE: trying to squeeze a non single-dimensional axis returns ValueError

Original Array: [[[1 2 3]]]
Original Shape: (1, 1, 3)
Squeezed Result: [1 2 3]
New Shape: (3,)

Original Shape: (1, 5, 1)
Squeezed Axis 0 Shape: (5, 1)


In [26]:
# Question 1: Create an array of ones with a shape of (3, 1, 2). Squeeze it and check its new shape.
arr = np.ones((3,1,2))
print("Original array shape:",arr.shape)
sq = np.squeeze(arr)
print("New Shape:",sq.shape)

# Question 2: Write a snippet that safely uses squeeze() on an array of shape (1, 1, 5) to get a target shape of (1, 5).
arr = np.zeros((1,1,5))
print("\nOriginal array shape:",arr.shape)
sq = np.squeeze(arr,axis=1)
print("New Shape:",sq.shape)

Original array shape: (3, 1, 2)
New Shape: (3, 2)

Original array shape: (1, 1, 5)
New Shape: (1, 5)
