In [ ]:
#arithematic operations: can be performed either between elements or an array and an element
import numpy as np

arr = np.array([10, 20, 30, 40])
result = arr + 5    #adds 5 to each and every element of the array
print(result)

# print(arr/0): would return an array [inf,inf,inf,inf] if arr has all non-zero number in it along with a RunTimeWarning
#               it would returns nan for every zero element in the array

#arith operations among arrays of same size.
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

added = arr1 + arr2
multiplied = arr1 * arr2

print("\nAddition:", added)
print("Multiplication:", multiplied)

#performing arithmatic operations on arrays of different sizes throws a ValueError

#simple division (/): translated the data type to float
#floor division (//): performs integer floor division

#multiplication in 2D array
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print("\nSimple multipliction of matrices(using *):\n",arr1*arr2)
print("Performing matrix multiplication on matrices:\n",arr1@arr2) #also np.matmul(arr1,arr2)

[15 25 35 45]

Addition: [11 22 33]
Multiplication: [10 40 90]

Simple multipliction of matrices(using *):
 [[ 5 12]
 [21 32]]
Performing matrix multiplication on matrices:
 [[19 22]
 [43 50]]


In [14]:
# Question 1: Create an array of values from 1 to 5. Multiply the entire array by 3 and then subtract 2 from the result.
arr = np.array([1,2,3,4,5])
new_arr = 3*arr - 2
print("New Array:\n",new_arr)

# Question 2: Create two 2D matrices of shape (2, 2). Perform element-wise division between them.
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[5,10],[15,20]])
new_matrix = arr1/arr2
print("\nNew Array:\n",new_matrix)

New Array:
 [ 1  4  7 10 13]

New Array:
 [[2. 2.]
 [2. 2.]]


In [ ]:
#Universal functions(ufuncs): highly optimized functions provided by NumPy that perform fast element-wise operations on arrays
#IMP NOTE: these are faster because the ufunc offloads the calculations into a C code which bypasses the constant checking of the data type which the Python interpreter would have done instead

#trigonometric fucntions: np.sin(), np.cos(), np.tan(), inverse: np.arcsin(), np.arccos(), np.arctan()
angles = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(angles)
print(sin_values)

#exp and log fucntions
arr = np.array([1, 2, 3])
exp_arr = np.exp(arr)        # calculates e^x
log_arr = np.log(exp_arr)    # calculates natural log (ln)  (for any log base n we simply write logn(): eg-> log10(10) = 1)

print("\nExponential:", exp_arr)
print("Logarithmic:", log_arr)

#using standard math module on a numpy array throws TypeError

[0.0000000e+00 1.0000000e+00 1.2246468e-16]

Exponential: [ 2.71828183  7.3890561  20.08553692]
Logarithmic: [1. 2. 3.]


In [ ]:
# Question 1: Given arr = np.array([1, 4, 9, 16]), use a NumPy ufunc to compute the element-wise square root of the entries.
arr = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr)     #for -ve numbers it returns nan along with RunTimeWarning
print("Element wise-Square root:\n",sqrt_arr)

# Question 2: Create an array of values [-2, -1, 0, 1, 2] and apply a ufunc that extracts their absolute values.
arr = np.array([-2, -1, 0, 1, 2])
abs_arr = np.abs(arr)
print("\nAbsoulte elements of array:\n",abs_arr)

Element wise-Square root:
 [1. 2. 3. 4.]

Absoulte elements of array:
 [2 1 0 1 2]


In [ ]:
#aggregate functions: perform operations on entire array and returns a single summary metric

arr = np.array([1,2,3,4,5])
print("Sum:",arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())

#aggregating along specific axis in multidimensional arrays
matrix = np.array([[1, 2],
                   [3, 4]])
row_sums = matrix.sum(axis=1) # if axis is not mentioned, it flattens the array and returns the max over every element
col_sums = matrix.sum(axis=0)

print("\nRow-wise Sums (Axis 1):", row_sums)
print("Col-wise Sums (Axis 0):", col_sums)

#keepdims attribute: using keepdims=True attribute along with an aggregate function returns an array of the same shape without collapsing the shape of the array. 
# it sets the dim of remaining axis as 1
row_sums_kd = matrix.sum(axis=1,keepdims=True)
print("\nShape of new array:",row_sums_kd.shape)

Sum: 15
Mean: 3.0
Max: 5

Row-wise Sums (Axis 1): [3 7]
Col-wise Sums (Axis 0): [4 6]

Shape of new array: (2, 1)


In [31]:
# Question 1: Create a 3x3 matrix containing values from 1 to 9. Compute the maximum value along each individual column.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Max along col 1:",np.max(arr,axis=0))

# Question 2: Create a 2D array and compute its total standard deviation using np.std().
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
std_arr = np.std(arr)
print("\nTotal Standard deviation:",std_arr)

Max along col 1: [7 8 9]

Total Standard deviation: 2.581988897471611


In [35]:
#argmax() & argmin(): returns indices of the max or min value in the array instead of their values.

arr = np.array([10, 42, 5, 18, 99, 23])
max_index = arr.argmax()
min_index = arr.argmin()

print("Index of Max Value:", max_index)
print("Actual Max Value:", arr[max_index])
print("Index of Min Value:", min_index)

#for 2D arrays 
matrix = np.array([[15, 88, 20],[40, 12, 65]])
max_indices_col = matrix.argmax(axis=0)
print("\nMax Row Indices per Column (Axis 0):", max_indices_col)    #returns row-wise indices where max values are present 

Index of Max Value: 4
Actual Max Value: 99
Index of Min Value: 2

Max Row Indices per Column (Axis 0): [1 0 1]


In [41]:
# Question 1: Given arr = np.array([5, 2, 9, 9, 4]), what does arr.argmax() return?
arr = np.array([5, 2, 9, 9, 4])
print(np.argmax(arr))   #returns the index of the max element of array

# Question 2: Create a 3x3 matrix and find the index positions of the minimum values along each row.
matrix = np.array([[14,2,32],[44,52,68],[71,28,90]])
print("\nThe minimum values at each row are at indices:",matrix.argmin(axis=1))

2

The minimum values at each row are at indices: [1 0 1]
