In [5]:
#broadcasting: It allows arithmetic operations to be performed between arrays of different shapes 
#without creating unnecessary copies of the data in memory. For two arrays to be compatible for broadcasting
    #they are completely of the same size   
    #one of the dimensions is 1

import numpy as np

arr = np.array([1, 2, 3])
result = arr * 2    #numpy treats 2 as an array of shape (1,) -> [2] and stretches ot to array of shape (3,) -> [2,2,2]
print(result)

#operation among 1D and 2D arrays
matrix = np.array([[10, 20, 30],[40, 50, 60]])  # Shape: (2, 3)
row_vector = np.array([1, 2, 3])   # Shape: (3,)

result = matrix + row_vector
print("\n",result)

#broadcasting two vectors together
col_vec = np.array([[1], [2], [3]]) # Shape: (3, 1)                     => stretched to [[1,1],[2,2],[3,3]]
row_vec = np.array([10, 20])        # Shape: (2,) -> padded to (1, 2)   => stretched to [[10,20],[10,20],[10,20]]

result = col_vec + row_vec
print("\n",result)

[2 4 6]

 [[11 22 33]
 [41 52 63]]

 [[11 21]
 [12 22]
 [13 23]]


In [10]:
# Question 1: Given a matrix A of shape (4, 3), what shape must a 1D row vector be to safely broadcast across A?
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([1,2,3])           
sum = A + B
print("The sum is:\n",sum)
print("Hence the required shape is:",B.shape)

# Question 2: Write a snippet that creates a column vector of shape (4, 1) containing numbers 1 to 4, and adds it to a row vector of shape (3,) containing tens [10, 20, 30].
col1 = np.array([[1],[2],[3],[4]])
arr = np.array([10,20,30])
sum = col1 + arr
print("\nThe required sum is:\n",sum)

The sum is:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
Hence the required shape is: (3,)

The required sum is:
 [[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
