In [ ]:
#np.where(): helps us to scan an array for a condition and returns the values if condition is True
import numpy as np

arr = np.array([10,5,20,3,15])
result = np.where(arr > 10, arr, -1) #np.where(<condition>, <value to return if cond True>, <value to return if cond False>)
print(result)

#only giving condition 
arr = np.array([10, 5, 20, 3, 20])
indices = np.where(arr == 20)   #returns a tuple of arrays containing the index positions where the condition evaluates to True
print("\n",indices)

#array passed itself
arr = np.array([10,0,2,-37,0])
result = np.where(arr)  #returns indices of all truthly(non-zero) values in the array
print("\nResult:",result)

[-1 -1 20 -1 15]

 (array([2, 4]),)

Result: (array([0, 2, 3]),)


In [12]:
# Question 1: Given scores = np.array([45, 88, 72, 30, 95]), use np.where to create an array containing "Pass" for scores >= 50 and "Fail" otherwise.
scores = np.array([45,88,72,30,95]) 
result = np.where(scores>=50,"Pass","Fail")
print("Result:",result)

# Question 2: Find the coordinate indices of all negative numbers in a 2D matrix.
arr = np.array([[15, -3, 8],[ -7, 0, 12],[ 4, -19, -5]])
coord = np.where(arr<0)
print("\nThe indices of all the negative numbers is:",coord)  #the tuple has two tuples 1)row indices 2)column indices

Result: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass']

The indices of all the negative numbers is: (array([0, 1, 2, 2]), array([1, 0, 1, 2]))


In [20]:
#sorting: sorting can be done in two ways:
    #1> np.sort(<arr>) -> sorts the array in-place 

import numpy as np

arr = np.array([10,2,34,28,17])
sort_arr = np.sort(arr)
print("Sorted array:",sort_arr)

    #2> np.argsort(<arr>) -> returns a new array containing the order of indices of the sorted arrangement of the array

arr = np.array([10,2,37,27,19])
sorted_ind = np.argsort(arr)
print("\nThe indices in sorted form are:",sorted_ind)
print("The sorted array is:",arr[sorted_ind])
print("while the original array still remains:",arr)

matrix = np.array([[15,2],[32,14]])
sorted_matrix = np.sort(matrix)
arg_sort_matrix = np.argsort(matrix)
print("\nSorting 2D array using sort():\n",sorted_matrix)
print("\nSorting 2D array using argsort():\n",arg_sort_matrix)

#IMP NOTE: np.sort(arr) v\s arr.sort()

#np.sort(arr): it is a function which returns a new copy of the sorted array
arr = np.array([20,3,60,27,86]) 
sort_arr = np.sort(arr)
print("\nThe result of np.sort() is the sorted array:",sort_arr)
print("Original array after sorting:",arr)

#arr.sort(): it is a method which sorts the array in-place and returns None
arr = np.array([40,37,20,57,2,13])
result = arr.sort()
print("\nThe result of arr.sort():",result,"and sorted array:",arr)
print("Original array:",arr)

#sorting in descending order

#using np.sort()
arr = np.array([40,37,20,57,2,13])
des_arr = np.sort(arr)[::-1]    #reverse the sorted array
print("\nDescending order of array:",des_arr)

#using np.argsort()
arr = np.array([40,37,20,57,2,13])
des_arr = np.argsort(-arr)  #since it returns only indices and the more magnitude of -ve numbers the least is considered their value 
print("Descending order of array:",arr[des_arr])

Sorted array: [ 2 10 17 28 34]

The indices in sorted form are: [1 0 4 3 2]
The sorted array is: [ 2 10 19 27 37]
while the original array still remains: [10  2 37 27 19]

Sorting 2D array using sort():
 [[ 2 15]
 [14 32]]

Sorting 2D array using argsort():
 [[1 0]
 [1 0]]

The result of np.sort() is the sorted array: [ 3 20 27 60 86]
Original array after sorting: [20  3 60 27 86]

The result of arr.sort(): None and sorted array: [ 2 13 20 37 40 57]
Original array: [ 2 13 20 37 40 57]

Descending order of array: [57 40 37 20 13  2]
Descending order of array: [57 40 37 20 13  2]


In [27]:
# Question 1: Given arr = np.array([12, 4, 8, 15, 1]), use np.argsort() to find the index of the second smallest element.
arr = np.array([12, 4, 8, 15, 1])
sort_ind = np.argsort(arr)
print("The index of the second smallest number is:",sort_ind[1])

# Question 2: Create a 2D matrix of shape (3, 3) with random integers and sort it along its columns (axis=0).
arr = np.array([[10,27,1],[2,40,37],[36,5,19]])
sort_arr = np.sort(arr,axis=0)
print("Original array:\n",arr)
print("The sorted matrix in column form is:\n",sort_arr)

The index of the second smallest number is: 1
Original array:
 [[10 27  1]
 [ 2 40 37]
 [36  5 19]]
The sorted matrix in column form is:
 [[ 2  5  1]
 [10 27 19]
 [36 40 37]]


In [ ]:
#np.searchsorted(): returns an array of indices where the new elements have to be inserted in order to maintane their sorted order.

arr = np.array([1,15,20,37,69,102])
index = np.searchsorted(arr,[23,34,110])
print("The indices at which [23, 34, 110] have to be inserted are:",index)

#23 must come at 3rd index -> between 20 and 37
#34 must come at 3rd index -> between 20 and 37
#110 must come at 6th index -> at the end after 102

#IMP NOTE: if your source array isn't already sorted, it will return incorrect insertion indices without throwing an error.
        #  it uses binary search to find location taking O(log(n)) time

#np.unique(): returns a new array of all unique elements in a sorted manner
arr = np.array([38,2,49,16,2,43,16,92,2,16])
uniq = np.unique(arr)
print("\nOriginal array:",arr)
print("Unique array:",uniq)

#works also with strings
data = np.array(['cat', 'dog', 'cat', 'bird', 'dog', 'dog'])
unique_vals, counts = np.unique(data, return_counts=True)   #it returns two things in the form of a tuple: 1) the sorted set of elements 
print("Unique Elements:", unique_vals)                                                                  #  2) the number of times each value is repeated 
print("Counts:", counts)                                    #there also is a parameter named return_index which when set to True returns the indices of the first appearance of an element in an array

#unique matrices
arr = np.array([[1,2,3,2,1],[4,6,5,5,6],[7,9,8,7,9]])
uniq_mat = np.unique(arr)
print("\n",uniq_mat)     #it flattens the array if no parameter passed 
uniq_row = np.unique(arr,axis=1)
print("\n",uniq_row)

The indices at which [23, 34, 110] have to be inserted are: [3 3 6]

Original array: [38  2 49 16  2 43 16 92  2 16]
Unique array: [ 2 16 38 43 49 92]
Unique Elements: ['bird' 'cat' 'dog']
Counts: [1 2 3]

 [1 2 3 4 5 6 7 8 9]

 [[1 1 2 2 3]
 [4 6 5 6 5]
 [7 9 7 9 8]]


In [52]:
# Question 1: Given arr = np.array([1, 1, 2, 3, 3, 3, 4]), use np.unique to return only the values that appeared, along with their first occurrence index positions.
arr = np.array([1, 1, 2, 3, 3, 3, 4])
set = np.unique(arr,return_index=True)
print("The unique array is:",set[0],"and the index of their first appearance is:",set[1])

# Question 2: Given a sorted threshold array [0.2, 0.5, 0.8], determine where the scalar value 0.6 lands using np.searchsorted().
arr = np.array([0.2,0.5,0.8])
where = np.searchsorted(arr,[0.6])
print("\nThe element 0.6 will be placed at index:",where[0])

The unique array is: [1 2 3 4] and the index of their first appearance is: [0 2 3 6]

The element 0.6 will be placed at index: 2
