In [12]:
#Permuting matrix: for matrices of 2 dim, to change the order of elements we use np.transpose() function. 
#                  But for matrices with dimesnions more than 3, we use permute(pass a tuple with new dimensions in it)

import numpy as np

# A tensor is a multi-dimensional grid of numbers
tensor = np.ones((2, 3, 4))

permuted = np.transpose(tensor, axes=(1, 2, 0)) # Permute axes: Axis 1 becomes Axis 0, Axis 2 becomes Axis 1, Axis 0 becomes Axis 2
#by default it transposes the matrice's shape from (a,b,c,....x,y,z) to (z,y,x....c,b,a)
print("Original tensor:\n",tensor)
print("Original tensor's shape:",tensor.shape)
print("\nPermuted shape:\n",permuted)
print("Permuted Shape:", permuted.shape)

#Calculating the Hermitian Transpose (Transpose Conjugate[Tranjugate])
matrix = np.array([[1+2j,3-4j,5],[6j,7,8+1j]])
tranj_matrix = matrix.conj().T
print("\nThe conjugate transpose of the given matrix is:",tranj_matrix)

Original tensor:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Original tensor's shape: (2, 3, 4)

Permuted shape:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
Permuted Shape: (3, 4, 2)

The conjugate transpose of the given matrix is: [[1.-2.j 0.-6.j]
 [3.+4.j 7.-0.j]
 [5.-0.j 8.-1.j]]


In [13]:
# Question 1: Create a 1D array of numbers 1 to 4. Reshape it to (4, 1) and then transpose it. What is the final shape?
arr = np.array([1,2,3,4])
arr1 = np.reshape(arr,(4,1))
t_arr = arr1.T
print("original Shape:",arr.shape)
print("Reshaped shape:",arr1.shape)
print("The final shape is:",t_arr.shape)

# Question 2: Create a 3D array of shape (2, 5, 10). Transpose it so that the final shape is (10, 2, 5)
arr = np.ones((2,5,10))
arr1 = np.transpose(arr,axes=(2,0,1))
print("\nOriginal Shape:",arr.shape)
print("New Shape:",arr1.shape)

original Shape: (4,)
Reshaped shape: (4, 1)
The final shape is: (1, 4)

Original Shape: (2, 5, 10)
New Shape: (10, 2, 5)


In [34]:
#determinant of matrix
A = np.array([[4,7],[2,6]])
det = np.linalg.det(A)
print("The determinant of the given matrix is:",det)

#determinant of multi-dimensional arrays
matrix = np.array(
    [[[1, 2, 3],
      [0, 4, 5],
      [1, 0, 6]],
      
      [[2, 5, 1],
       [3, 0, 2],
       [4, 1, 3]]]
)
#it will simply treat it as a batch of 2 3x3 matrices
det = np.linalg.det(matrix)
print("\nThe determinant of the given matrix of shape:",matrix.shape,"is:",det)

#inverse of a matrix
inv = np.linalg.inv(A)
print("\nThe inverse of the given matrix:\n",inv)

#if the matrix is Singular (i.e det(A) = 0) then np.linalg.inv(A) returns LinAlgError: Singular Matrix

#IMP NOTE: Solving sets of linear equations Ax = b
#Generallyt these questions are solved by first finding out the value of inv(A) and then multiplying it with b, we get
# x = b.inv(A)
#but using x = np.linalg.inv(A)@b is a very expensive operation to perform so we instead use np.linalg.solve(A,b)

#let equations be:
    # x+2y+3z=14
    # 2x+5y+2z=18
    # x+3y+z=11

A = np.array([[1,2,3],[2,5,2],[1,3,1]])
b = np.array([14,18,11])

x,y,z = np.linalg.solve(A,b)
print("\nThe values of x:",x,", y:",y,"and z:",z)

The determinant of the given matrix is: 10.000000000000002

The determinant of the given matrix of shape: (2, 3, 3) is: [22. -6.]

The inverse of the given matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

The values of x: -4.5 , y: 4.0 and z: 3.5


In [35]:
# Question 1: Create the matrix M = ((1,2),(3,4)). Compute its determinant.
M = np.array([[1,2],[3,4]])
det_M = np.linalg.det(M)

#to get round off answer
print("Rounded off determinant of the matrix is:",np.round(det_M,decimals=2))

# Question 2: Try calculating the inverse of a matrix full of zeros. Write down what specific exception is raised.
try:
    zero = np.zeros((3,3))
    inv = np.linalg.inv(zero)

    print("\nThe inverse of the given null array is:",inv)

except:
    print("\nLinAlg:Singular Matrix error occured")

Rounded off determinant of the matrix is: -2.0

LinAlg:Singular Matrix error occured


In [40]:
#Eigen Values & Eigen Vectors

A = np.array([[1, 2],
              [2, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)    #also can use .eigh() which is specialized for hermitian matrices and is more stable, faster and gurantees purely real eigen values

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors Matrix:\n", eigenvectors)

#Proof A(v) = lambda(v)
L = eigenvalues[0]
v = eigenvectors[:,0]   #eigenvectors are stacked as columns 

Av = A @ v
Lv = L * v

print("\nA @ v:", Av)
print("lambda * v:", Lv)
print("Match?:", np.allclose(Av, Lv))

#NOTE: for certain arrays, eigenvalues and eigenvectors may contain complex numbers so numoy automatically shifts the output array dtype to complex128

Eigenvalues:
 [ 3.+0.j -1.+0.j]

Eigenvectors Matrix:
 [[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]

A @ v: [2.12132034+0.j 2.12132034+0.j]
lambda * v: [2.12132034+0.j 2.12132034+0.j]
Match?: True


In [45]:
# Question 1: Create a diagonal matrix M = np.diag([4, 5, 6]). Run np.linalg.eig(M) on it. What do you notice about its eigenvalues?
M = np.diag([4,5,6])
eigval, eigenvec = np.linalg.eig(M)
print("The eigen values for the given matrix is:\n", eigval)

# Question 2: Given a matrix B, write a script snippet that slices out the second eigenvector column and prints its scalar length (magnitude).
import numpy as np
B = np.array([[4, 1, 0],[2,5,0],[0, 0, 6]])

evalues, evectors = np.linalg.eig(B)
second_eigenvector = evectors[:, 1]
magnitude = np.linalg.norm(second_eigenvector)

print("Second Eigenvector:\n", second_eigenvector)
print("\nScalar Length (Magnitude):", magnitude)


The eigen values for the given matrix is:
 [4.+0.j 5.+0.j 6.+0.j]
Second Eigenvector:
 [-0.4472136 +0.j -0.89442719+0.j  0.        +0.j]

Scalar Length (Magnitude): 0.9999999999999999
