In [ ]:
#Modern Random Engine:

import numpy as np

#initializing the modern random number generator engine
rng = np.random.default_rng(seed=42) #seed parameter (default = None) allows us to set a value from which it starts generating numbers.
                                     #It ensures that the value generated do not change until and unless:
                                        # 1)Your numpy version is changed
                                        # 2)You change the order of your code (by adding or removing lines from it)
                                        # 3)You run your program by multithreading
                                     #Two different generators with the same seed generate the same values if the above conditions are satisfied 

# Generate 3 uniform random floats between 0.0 (inclusive) and 1.0 (exclusive)
random_floats = rng.random(size=3)
print("Uniform Floats: ", random_floats)

# Generate a 2x3 matrix of random integers between 1 and 100
random_ints = rng.integers(low=1, high=101, size=(2, 3))
print("\nRandom Integers Matrix:\n", random_ints)

#Pre-defining mean(centre) and standard deviation(spread)
normal_samples = rng.normal(loc=0.0,scale=1.0,size=(3,5))
norm_acc_samples = rng.normal(loc=0.0,scale=1.0,size=1000)     #this result is more accurate because it has 1000 elements in it while the array before has only 15
print("Mean =",np.mean(normal_samples))
print("More Accurate Mean =",np.mean(norm_acc_samples))
print("Std Deviation =",np.std(normal_samples))
print("More Accurate Std Deviation =",np.std(norm_acc_samples))

Uniform Floats:  [0.77395605 0.43887844 0.85859792]

Random Integers Matrix:
 [[ 9 70 21]
 [10 53 98]]
Mean = 0.09693077533099509
More Accurate Mean = -0.030457016352933935
Std Deviation = 0.6417394149490492
More Accurate Std Deviation = 0.9874139480856606


In [103]:
# Question 1: Use the modern rng pattern to simulate rolling a standard 6-sided die 20 times.
rng = np.random.default_rng(seed=None)

choice = rng.integers(low=1,high=7)
print("The dice rolled:",choice)
print("Re-run to re-roll!")

# Question 2: Generate a 1D array of 5 elements sampled from a standard uniform distribution over the range [-5.0, 5.0).
random_ele = rng.integers(low=-5,high=5,size=5)
print("\nThe randomly generated 5 sized arrays are:",random_ele)

The dice rolled: 3
Re-run to re-roll!

The randomly generated 5 sized arrays are: [ 2 -5 -3 -1  2]


In [146]:
#Some more functions of Modern random generator np.random.default_rng()

#choice(): choosing among a group of choices with custom probability.
outcomes = ['Heads', 'Tails']
print(rng.choice(outcomes, size=5, p=[0.7, 0.3]))  #returns an array of 5 choices with heads having 70% probability to occur


#shuffle(): randomly shuffles the array in-place
arr = np.array([10, 20, 30, 40, 50])
rng.shuffle(arr)
print(arr)

#permutation(): randomly shuffles the array and returns a copy of the same.
arr = np.array([10, 20, 30, 40, 50])
random_arr = rng.permutation(arr)
print(random_arr)

['Heads' 'Heads' 'Heads' 'Heads' 'Heads']
[30 40 20 50 10]
[30 40 20 10 50]
