In [1]:
import numpy as np

#Storing an array into a CSV or TSV file
matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

# Save the passed array (either 1D or 2D) as a standard comma-separated text file (NOTE: if ndim(arr) > 2 then it will throw a ValueError)
# fmt='%.2f' truncates floats to 2 decimal places, or use '%d' for integers
np.savetxt('dataset.csv', matrix, delimiter=',', fmt='%d')  #also has parameters such as header, footer

#Reading data from the file
arr = np.loadtxt('dataset.csv',delimiter=',',skiprows=0)     #skiprows parameter states the number of rows to be skipped before extracting the data
print(arr)

[[10. 20. 30.]
 [40. 50. 60.]]


In [2]:
#Storing and retrieving data from a binary file -> binary files freezes your data type of the data once you store it.
large_matrix = np.random.randn(1000,1000)   #creates a 2D matrix of size 1000x1000 containing 1 million elements

# np.save('file_name',matrix_name) -> stores the data in the array in the given binary file
np.save('highres_matrix.npy',large_matrix)

# np.load('file_name') -> retrieves the data in the form of array from the binary file.
loaded_matrix = np.load('highres_matrix.npy')

print("The shape of the matrix is:",loaded_matrix.shape)

#NOTE: it is a better way of extracting data from the binary files as compared to pickling (pickle) in Python since it is more time as well as memory efficient.

The shape of the matrix is: (1000, 1000)


In [3]:
# Question 1: Create a random 2D array of floats. Save it using np.savetxt() with a tab character (\t) as your custom column separator.  
rng = np.random.default_rng(seed=21)
matrix = rng.uniform(low=1.0,high=100.0,size=(4,4))

np.savetxt("practiceOfFileHan.csv",matrix,delimiter="\t",fmt="%.2f")

# Question 2: Write a script snippet that saves a 1D array to a .npy file, deletes the array variable name from active Python memory using del, 
# and reloads it cleanly into a brand new variable namespace.

arr = np.array([1,2,3,4,5,6,7])
np.save("PracOfbinFileHan.npy",arr)

del arr
var = np.load("PracOfbinFileHan.npy")

try:
    print("The original array is:\n",arr)
except Exception as e:
    print("Exception faced is:",e)

print("The extracted array is:\n",var)

Exception faced is: name 'arr' is not defined
The extracted array is:
 [1 2 3 4 5 6 7]


In [4]:
#Both the above discussed methods to entry the array in a file bin/text both, always by default over-write the file if it already exists.

#to prevent to do so in case of text files(np.savetxt())

arr = np.array([100,110,120])
with open("dataset.csv","ab") as f:
    np.savetxt(f,arr[np.newaxis,:],delimiter=',',fmt="%d")       # by default it stores each and every element of the array in the form of row
                                                                 # hence newaxis is added to add all elements in the same row