In [1]:
# np.loadtxt(): is a fast, lightweight parser that works great for clean, well formated numerical text files.
# But once we face a messy file(file with disorganized, poorly formated or inconsistent data) we can't use this method anymore.

# np.genfromtxt(): hence we have this method for parsing messy files

import numpy as np

# inconsistent data in file = [[1.5,2.1,3.7],
#                              [3.3,4.2,___],
#                              [5.3,6.0,7.9]]

data_loaded =  np.genfromtxt('parsingMessyFiles.csv',delimiter=',',filling_values=-1)   # default value of filling_values is NaN (Not a Number)
                                                                                        # any operation performed with NaN always results in NaN

#if we had used loadtxt() then it would have returned a ValueError
print("Parsed data:\n",data_loaded)

#IMP NOTE: np.loadtxt() is much more faster than np.genfromtxt() for larger datasets since it assumes that the file being passed is already clean, well formated. 

Parsed data:
 [[ 1.5  2.1  3.7]
 [ 3.3  4.2 -1. ]
 [ 5.3  6.   7.9]]


In [4]:
# Question 1: Write a statement using np.loadtxt() that reads a file named data.txt separated by semicolons (;) 
# and extracts only the second and fourth columns (indices 1 and 3).

data = np.array([[241038,100000,98.77,1234567890],[241039,120000,56.45,9876054321],[241040,125000,100.00,98760545678]])

np.savetxt('data.txt',data,delimiter=';',fmt="%.2f",header="EnrollNo.;Fees;Score;PhoneNum")

loaded_data = np.loadtxt('data.txt',delimiter=';',skiprows=1,usecols=(1,3))
print("The required array is:\n",loaded_data)


# Question 2: Create a snippet using np.genfromtxt() that uses a custom converter dictionary to strip $ signs from a column during import 
# (e.g., converting "$25.50" to 25.50).

import numpy as np

# 1. Define the correct column names and data types (Float, Integer, Unicode String)
store_dtype = [("Price", "f8"), ("Quantity", "i4"), ("Stock", "U15")]

# 2. Structure your sample dataset using dtype=object to keep mixed types intact
data = np.array([
    ["$25.50", 10, "In_Stock"],
    ["$105.00", 5, "Low_Stock"],
    ["$3.99", 100, "In_Stock"],
    ["$0.50", 0, "Out_of_Stock"],
    ["$1250.75", 2, "Low_Stock"]
], dtype=object)

# 3. Save array rows to a text file separated by semicolons
np.savetxt('storeMang.txt', data, delimiter=";", fmt='%s')

# 4. FIX: Robust converter that strips '$' safely regardless of NumPy version
def clean_money(val):
    if isinstance(val, bytes):
        val = val.decode('utf-8')  # Converts bytes to string if needed
    return float(val.replace('$', ''))

# 5. Parse the file back, running the converter strictly on the first column (index 0)
value = np.genfromtxt('storeMang.txt', delimiter=";", 
                      converters={0: clean_money}, dtype=store_dtype)

# 6. View the structured array output
print("\nParsed Array:\n", value)


The required array is:
 [[1.00000000e+05 1.23456789e+09]
 [1.20000000e+05 9.87605432e+09]
 [1.25000000e+05 9.87605457e+10]]

Parsed Array:
 [(2.55000e+01,  10, 'In_Stock') (1.05000e+02,   5, 'Low_Stock')
 (3.99000e+00, 100, 'In_Stock') (5.00000e-01,   0, 'Out_of_Stock')
 (1.25075e+03,   2, 'Low_Stock')]


In [3]:
# np.loadtxt(): is a fast, lightweight parser that works great for clean, well formated numerical text files.
# But once we face a messy file(file with disorganized, poorly formated or inconsistent data) we can't use this method anymore.

# np.genfromtxt(): hence we have this method for parsing messy files

import numpy as np

# inconsistent data in file = [[1.5,2.1,3.7],
#                              [3.3,4.2,___],
#                              [5.3,6.0,7.9]]

data_loaded =  np.genfromtxt('parsingMessyFiles.csv',delimiter=',',filling_values=-1)   # default value of filling_values is NaN (Not a Number)
                                                                                        # any operation performed with NaN always results in NaN

#if we had used loadtxt() then it would have returned a ValueError
print("Parsed data:\n",data_loaded)

#IMP NOTE: np.loadtxt() is much more faster than np.genfromtxt() for larger datasets since it assumes that the file being passed is already clean, well formated. 

Parsed data:
 [[ 1.5  2.1  3.7]
 [ 3.3  4.2 -1. ]
 [ 5.3  6.   7.9]]
