In [2]:
import numpy as np

# Q1. Create a NumPy array from a single floating-point number (e.g., 42.0).
# How do you verify that it is structurally 0-dimensional using an array attribute?

arr1 = np.array(42.0)
print("The dimensions of the array is:",arr1.ndim)

The dimensions of the array is: 0


In [3]:
# Q2. Given an array arr = np.arange(10, dtype=np.int32), what will arr.strides return? Explain what that output means in bytes.

arr2 = np.arange(10,dtype=np.int32)
print("The .strides is a property which returns the tuple containing the number of bytes the computer needs to jump to reach from the start to the other end of the given axis.")
print("Here it would return",arr2.strides,"since column-wise to go from element 0 to next element 1 it requires to jump 4 bytes.")


The .strides is a property which returns the tuple containing the number of bytes the computer needs to jump to reach from the start to the other end of the given axis.
Here it would return (4,) since column-wise to go from element 0 to next element 1 it requires to jump 4 bytes.


In [4]:
# Q3. Given the array arr = np.array([10, 20, 30, 40, 50]), 
# write a slice expression to return the array in reverse order without allocating a brand new array copy in memory.

arr3 = np.array([10, 20, 30, 40, 50])
print("The given array in reverse order is:",arr3[::-1])

The given array in reverse order is: [50 40 30 20 10]


In [5]:
#Q4. If you execute sub_arr = arr[1:4] and then run sub_arr[0] = 99, what happens to the element at arr[1]? Explain the structural reason why.

arr4 = np.array([1,2,3,4,5,6,7,8,9,0])
sub_arr = arr4[1:4]
sub_arr[0] = 99
print("The element at arr4[1]:",arr4[1])
print("The original array also changes since slicing only returns us a view of the slice of the array and does not creates a new array in the memory.")

The element at arr4[1]: 99
The original array also changes since slicing only returns us a view of the slice of the array and does not creates a new array in the memory.


In [6]:
# Q5. Given a 3D matrix of shape (2, 3, 4),
# how can you flatten it into a 1D array view using a built-in array method without forcing NumPy to copy the underlying data payload?

arr5 = np.arange(24).reshape(2,3,4)
raveled = arr5.ravel()
print("The original array is:\n",arr5)
print("\nThe ravel returns a view of the flattened array which is:\n",raveled)

The original array is:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

The ravel returns a view of the flattened array which is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
# Q6. Create a random integer matrix of shape (5, 4). 
# Write a single line of code to calculate the minimum value present along each individual column. What is the shape of the resulting array?

rng = np.random.default_rng(seed=42)
arr6 = rng.integers(low=0,high=101,size=(5,4))
print("The original array is:\n",arr6)
ind_val_col = np.min(arr6,axis=0)
print("\nThe minimum values in each column are:",ind_val_col)

The original array is:
 [[ 9 78 66 44]
 [43 86  8 70]
 [20  9 53 98]
 [74 76 72 79]
 [51 12 84 45]]

The minimum values in each column are: [ 9  9  8 44]


In [8]:
# Q7. Write a plain Python function that squares a scalar, adds 10, and takes the square root.
# Convert this function into an element-wise NumPy universal function (ufunc).

import math

def fun(var):
    return math.sqrt(var**2 + 10)

np_fun = np.frompyfunc(fun,1,1)
arr = np.array([10,20,30,40,50,60])
print("The return value of the function for 15 is:",fun(15))
print("The value of arr passed in function is:\n",np_fun(arr))

The return value of the function for 15 is: 15.329709716755891
The value of arr passed in function is:
 [10.488088481701515 20.248456731316587 30.166206257996713
 40.124805295477756 50.0999001995014 60.08327554319921]


In [9]:
# Q8. You try to add an array of shape (3, 1) to an array of shape (1, 4).
# Does this throw an execution error? If it succeeds, what is the exact shape of the output matrix?

arr8_1 = np.arange(3).reshape(3,1)
arr8_2 = np.arange(4).reshape(1,4)

print("Sum:\n",arr8_1 + arr8_2)
print("Both the arrays stretch due to broadcasting.")

Sum:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
Both the arrays stretch due to broadcasting.


In [10]:
# Q9. You attempt to add an array of shape (4, 3) to an array of shape (4,). 
# State why this operation triggers a broadcasting value mismatch error, and fix the lower dimension array using np.newaxis.

arr9_1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr9_2 = np.array([1,2,3,4])

try:
    sum = arr9_1 + arr9_2
    print("Sum:",sum)

except:
    print("An error occured since the trailing (rightmost) element of the arrays are neither equal nor one of them is 1.")

#to fix it we use np.newaxis which adds a new single axis 
new_arr9_2 = arr9_2[:,np.newaxis]   #original shape = (4,1) -> resultant shape = (4,1) 
sum = arr9_1 + new_arr9_2
print("The corrected(broadcasting) sum is:\n",sum)

An error occured since the trailing (rightmost) element of the arrays are neither equal nor one of them is 1.
The corrected(broadcasting) sum is:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [11]:
# Q10. Given a 1D array [1, 2, 3, 4], which mathematical accumulation function will return the running cumulative product: [1, 2, 6, 24]?

arr10 = np.array([1,2,3,4])
req_arr = np.cumprod(arr10)     #np.cumprod(): calculates the cumulative product of the elements at a given axis
print("The required array is:",req_arr)

The required array is: [ 1  2  6 24]


In [12]:
# Q11. Given arr = np.array([5, -2, 3, -1, 0, 8]),
# write an np.where() statement that replaces all negative numbers with -99 and leaves all positive/zero numbers completely untouched.

arr11 = np.array([5,-2,3,-1,0,8])
neg_ind = np.where(arr11 < 0)
arr11[neg_ind] = -99
print("The updated array is:",arr11)

The updated array is: [  5 -99   3 -99   0   8]


In [13]:
# Q12. Given a 2D binary classification matrix:

# grid = np.array([[0, 1], 
#                  [1, 0]])
# What is the exact structural output format if you call np.where(grid == 1)?

arr12 = np.array([[0,1],[1,0]])
cond_arr = np.where(arr12 == 1)
print("The value:",cond_arr)
print("It returns a tuple of size:",len(cond_arr),"each for each row.")

The value: (array([0, 1]), array([1, 0]))
It returns a tuple of size: 2 each for each row.


In [14]:
# Q13. Given a random matrix of shape (4, 4), write a line of code using np.sort() to sort the values within each individual row in ascending order.

rng = np.random.default_rng(seed=2)
arr13 = rng.integers(low=1,high=101,size=(4,4))
asc = np.sort(arr13,axis=1)
print(asc)

[[ 11  27  30  84]
 [ 10  42  46  82]
 [ 34  61  73  82]
 [  6  19  89 100]]


In [15]:
# Q14. You have an array of strings names = np.array(['B', 'C', 'A']) and scores scores = np.array([90, 70, 85]).
# Use np.argsort() on the scores to sort the names array from the lowest score to the highest score.

names = np.array(['B','C','A'])
scores = np.array([90,70,85])
ind = np.argsort(scores)
print("The order of name of the students from highest to lowest is:",names[ind])

The order of name of the students from highest to lowest is: ['C' 'A' 'B']


In [16]:
# Q15. You have a pre-sorted lookup threshold reference list bounds = np.array([10, 20, 30, 40]). 
# Use np.searchsorted() to find where the numbers 15 and 35 should be placed to preserve order.

bounds = np.array([10,20,30,40])
order = np.searchsorted(bounds,[15,35])
print("The elements 15 and 35 must be placed at indices:",order[0],"and",order[1],"respectively")

The elements 15 and 35 must be placed at indices: 1 and 3 respectively


In [17]:
# Q16. Given a data log labels = np.array(['apple', 'banana', 'apple', 'apple', 'banana']), 
# write an extraction statement using np.unique() that simultaneously returns the distinct strings and their respective occurrence counts.

labels = np.array(['apple','banana','apple','apple','banana'])
tup = np.unique(labels,return_counts=True)
print("The distinct strings inside the array are:",tup[0],"and their counts are:",tup[1],"respectively.")

The distinct strings inside the array are: ['apple' 'banana'] and their counts are: [3 2] respectively.


In [18]:
# Q17. Given a 1D vector vec = np.array([1, 2, 3, 4]), you type vec.T. 
# What is the resulting shape? Explain why it did or did not turn into a column vector layout.

vec = np.array([1,2,3,4])
t_vec = vec.T
print("The original array's shape is:",t_vec.shape)
print("Transposing a 1D vector does nothing because it only has one axis.")

The original array's shape is: (4,)
Transposing a 1D vector does nothing because it only has one axis.


In [19]:
# Q18. Given an image batch tensor of shape (32, 224, 224, 3) representing (Batch, Height, Width, Channels), 
# use np.transpose() to rearrange the dimensions to match a machine learning framework standard: (Batch, Channels, Height, Width).

batch = np.empty((32,224,224,3))
new_batch = np.transpose(batch,axes=(0,3,1,2))
print("The shape of the updated branch is:",new_batch.shape)

The shape of the updated branch is: (32, 3, 224, 224)


In [20]:
# Q19. Define a structured array data type (dtype) named sensor_packet that contains three explicit named fields: 
# timestamp (64-bit integer), status (a 4-character string), and reading (64-bit float).

sensor_packet = [("Timestamp","int64"),("Status","U10"),("Reading","float64")]
data = [(12,"Done",20.12),(14,"Ongoing",3.52)]
logs = np.array(data,dtype=sensor_packet)
print("The new array with structured data type is:",logs)

The new array with structured data type is: [(12, 'Done', 20.12) (14, 'Ongoing',  3.52)]


In [21]:
# Q20. Given a structured array named logs constructed using your sensor_packet data type from Question 19, 
# which operation fetches a continuous column memory view: logs[0] or logs['reading']?

print("using log[0](returns the value of the record[row]):\n",logs[0])
print("\nusing log['Reading'](returns the value of the column Reading):\n",logs['Reading'])

using log[0](returns the value of the record[row]):
 (12, 'Done', 20.12)

using log['Reading'](returns the value of the column Reading):
 [20.12  3.52]


In [26]:
# Q21. Convert a standard multi-field structured array arr directly into an active record array (np.recarray) 
# so you can access a column named velocity using the dot attribute syntax arr.velocity.

movement = [("dist","f8"),("velocity","f8"),("time","i4")]
data = [(20.8,12.4,2),(12.3,2.0,2)]

arr21 = np.array(data,dtype=movement)
actual_arr = arr21.view(np.recarray)
print("Accessing the column velocity using its field name:\n",actual_arr["velocity"])

Accessing the column velocity using its field name:
 [12.4  2. ]


In [31]:
# Q22. Write a statement using the np.linalg submodule to calculate the determinant of a 3x3 matrix. 
# If the returned scalar is exactly 0.0, what will happen if you attempt to run np.linalg.inv()?

arr22_1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
arr22_2 = np.array([[1,0,0],[0,1,0],[0,0,0]])

det1 = np.linalg.det(arr22_1)
det2 = np.linalg.det(arr22_2)

print("The determinant of two matrices is:",det1,"and",det2)

try:
    print(np.linalg.inv(arr22_2))

except Exception as e:
    print('Trying to evaluate the inverse of a matrix whose determinant is zero throws us an exception:',e)

The determinant of two matrices is: 1.0 and 0.0
Trying to evaluate the inverse of a matrix whose determinant is zero throws us an exception: Singular matrix


In [35]:
# Q23. You need to find the vector x that satisfies the matrix equation Ax = b. 
# Write down the production-grade function call from np.linalg that computes this safely without explicitly calculating the costly inverse matrix A^-1.

A = np.array([[2,1,1],[1,-3,2],[3,2,-1]])
B = np.array([8,-11,11])

x = np.linalg.solve(A,B)

print("The resultant solution matrix is:\n",x)

The resultant solution matrix is:
 [0.875 4.875 1.375]


In [37]:
# Q24. The function call eigenvals, eigenvecs = np.linalg.eig(matrix) returns its values. 
# Write down the slice statement needed to extract the specific column eigenvector associated with the second entry in eigenvals

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenval, eigenvec = np.linalg.eig(matrix)

print("The column of eigenvector associated with the second entry in eigenvalues is:\n",eigenvec[:,1])

The column of eigenvector associated with the second entry in eigenvalues is:
 [-0.78583024+0.j -0.08675134+0.j  0.61232756+0.j]
